inherit_from:
  - .rubocop.unhound.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'db/migrate/*'
   - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  MaxLineLength: 100

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WhileUntilModifier:
  MaxLineLength: 100

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/EmptyMethod:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/DotPosition:
  EnforcedStyle: trailing
